name: metas-pocket-server

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}